version: '2.1'
services:
  jenkins:
    image: jenkins/jenkins:latest
    user: root
    ports:
      - 8080:8080
#      - 443:8443 # Enable for HTTPS connection
    container_name: jenkins-master
    volumes:
       - jenkins-master:/var/jenkins_home
    restart: unless-stopped
    environment: 
      - LANG=C.UTF-8
#      - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443 --httpsKeyStore="/var/jenkins_home/jenkins.jks" --httpsKeyStorePassword=***** # Enable for HTTPS connection
  agent:
    group_add:
      - 998
    image: jenkins/inbound-agent:latest # Enable for jnpl agent
    #image: jenkins/ssh-agent:latest # Enable for SSH agent
    container_name: jenkins-agent
    restart: unless-stopped
    user: root
    #expose:  # Enable for SSH agent
    #  - "22"
    extra_hosts:  # Enable for SSH agent
      - "host.docker.internal:host-gateway"
    depends_on:
       - jenkins
    volumes:
       - /usr/bin/docker:/usr/bin/docker
       - /var/run/docker.sock:/var/run/docker.sock
       - jenkins-agent:/home/jenkins/
    environment:
       - JENKINS_URL=http://jenkins:8080
       - JENKINS_AGENT_WORKDIR=/home/jenkins/
       - JENKINS_SECRET=************
       - JENKINS_AGENT_NAME=NodeA
       - JENKINS_AGENT_SSH_PUBKEY=*****
volumes:
  jenkins-master:
  jenkins-agent:

        



